### Excercici 1

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('matches.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50577 entries, 0 to 50576
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   best_of             50577 non-null  int64
 1   draw_size           50577 non-null  int64
 2   loser_age           50572 non-null  float64
 3   loser_entry         10303 non-null  object
 4   loser_hand          49558 non-null  object
 5   loser_ht            26990 non-null  float64
 6   loser_id            50577 non-null  int64
 7   loser_ioc           50577 non-null  object
 8   loser_name          50577 non-null  object
 9   loser_rank          47894 non-null  object
 10  loser_rank_points   47893 non-null  float64
 11  loser_seed          11534 non-null  object
 12  match_num           50576 non-null  float64
 13  minutes             4998 non-null   float64
 14  round               50576 non-null  object
 15  score               50577 non-null  object
 16  surface             50526 non-null  object
 17  tourney_date        50577 non-null  object
 18  tourney_id          50577 non-null  object
 19  tourney_level       50577 non-null  object
 20  tourney_name        50577 non-null  object
 21  winner_age          50571 non-null  float64
 22  winner_entry        6376 non-null   object
 23  winner_hand         50235 non-null  object
 24  winner_ht           32744 non-null  object
 25  winner_id           50577 non-null  float64
 26  winner_ioc          50577 non-null  object
 27  winner_name         50577 non-null  object
 28  winner_rank         48983 non-null  object
 29  winner_rank_points  48981 non-null  float64
 30  winner_seed         21629 non-null  object
 31  year                50574 non-null  float64
 32  Unnamed: 32         3 non-null      float64
dtypes: float64(10), int64(3), object(20)
memory usage: 12.7+ MB

/Users/psans/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (9,11,17,24,28,30) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
df.drop(['best_of', 'draw_size','loser_entry','loser_ht','loser_id','loser_rank_points',
         'loser_seed','match_num','minutes','score','tourney_date','tourney_id','winner_id',
         'winner_rank_points','Unnamed: 32'], axis=1, inplace=True)

In [4]:
df.isnull().sum()

loser_age            5
loser_hand        1019
loser_ioc            0
loser_name           0
loser_rank        2683
round                1
surface             51
tourney_level        0
tourney_name         0
winner_age           6
winner_entry     44201
winner_hand        342
winner_ht        17833
winner_ioc           0
winner_name          0
winner_rank       1594
winner_seed      28948
year                 3
dtype: int64

##### omplim les edats que falten amb la mitja

In [5]:
df['winner_age'].fillna(df['winner_age'].mean(), inplace=True)
df['loser_age'].fillna(df['loser_age'].mean(), inplace=True)

In [6]:
df = df.astype({'loser_age': int,'winner_age': int})

In [7]:
df

,loser_age,loser_hand,loser_ioc,loser_name,loser_rank,round,surface,tourney_level,tourney_name,winner_age,winner_entry,winner_hand,winner_ht,winner_ioc,winner_name,winner_rank,winner_seed,year
0,17,R,CRO,Mirjana Lucic,49.0,R128,Hard,G,Australian Open,19,NaN,R,170.0,SUI,Martina Hingis,1.0,1.0,2000.0
1,27,R,AUS,Kerry Anne Guse,133.0,R128,Hard,G,Australian Open,17,NaN,R,167.0,BEL,Justine Henin,63.0,NaN,2000.0
2,31,R,USA,Jolene Watanabe Giltz,118.0,R128,Hard,G,Australian Open,26,NaN,R,NaN,SVK,Karina Habsudova,53.0,NaN,2000.0
3,22,R,CRO,Silvija Talaja,23.0,R128,Hard,G,Australian Open,18,NaN,R,182.0,AUS,Alicia Molik,116.0,NaN,2000.0
4,24,R,ITA,Rita Grande,60.0,R128,Hard,G,Australian Open,22,NaN,R,165.0,THA,Tamarine Tanasugarn,72.0,NaN,2000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50572,21,R,TPE,Ya Hsuan Lee,298.0,RR,Clay,D,Fed Cup WG2 R1: ITA vs TPE,29,NaN,R,164.0,ITA,Sara Errani,110.0,NaN,2017.0
50573,24,R,GBR,Heather Watson,113.0,RR,Clay,D,Fed Cup WG2 R1: ROU vs GBR,25,NaN,R,168.0,ROU,Simona Halep,5.0,NaN,2017.0
50574,27,R,ROU,Sorana Cirstea,62.0,RR,Clay,D,Fed Cup WG2 R1: ROU vs GBR,25,NaN,R,NaN,GBR,Johanna Konta,7.0,NaN,2017.0
50575,25,R,GBR,Johanna Konta,7.0,RR,Clay,D,Fed Cup WG2 R1: ROU vs GBR,25,NaN,R,168.0,ROU,Simona Halep,5.0,NaN,2017.0
50576,24,R,GBR,Heather Watson,113.0,RR,Clay,D,Fed Cup WG2 R1: ROU vs GBR,26,NaN,R,181.0,ROU,Irina Camelia Begu,33.0,NaN,2017.0

In [8]:
for num in df['year'].index[df['year'].apply(np.isnan)]:
    print(num)
df[np.isnan(df.year)]

11906
11912
11914

,loser_age,loser_hand,loser_ioc,loser_name,loser_rank,round,surface,tourney_level,tourney_name,winner_age,winner_entry,winner_hand,winner_ht,winner_ioc,winner_name,winner_rank,winner_seed,year
11906,26,NaN,PHI,Francesca La&#39,O,NaN,6-2 6-3,2003-D069,D,24,16.4298425736,NaN,R,201420,IND,Sania Mirza,36.0,NaN
11912,18,NaN,POC,Gurianna Korinihona,NaN,RR,Hard,D,Fed Cup G2 RR: PHI vs POC,26,NaN,NaN,NaN,PHI,Francesca La&#39,O,NaN,NaN
11914,19,NaN,KGZ,Yulia Klimchenko,NaN,RR,Hard,D,Fed Cup G2 RR: PHI vs KGZ,26,NaN,NaN,NaN,PHI,Francesca La&#39,O,NaN,NaN

In [9]:
df.dropna(subset=['year'],inplace=True)

In [10]:
df.to_csv('tennis.csv')